/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerId = IDL.Text;
export const PlayerStats = IDL.Record({
  'averagePosition' : IDL.Opt(IDL.Float64),
  'bestTime' : IDL.Opt(IDL.Nat),
  'racesCompleted' : IDL.Nat,
});
export const PlayerProfile = IDL.Record({
  'id' : PlayerId,
  'nickname' : IDL.Text,
  'stats' : PlayerStats,
});
export const Time = IDL.Int;
export const RaceResult = IDL.Record({
  'completionTime' : IDL.Nat,
  'playerId' : PlayerId,
  'trackId' : IDL.Nat,
  'timestamp' : Time,
  'position' : IDL.Nat,
});
export const TrackDifficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Track = IDL.Record({
  'id' : IDL.Nat,
  'difficulty' : TrackDifficulty,
  'name' : IDL.Text,
  'length' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createPlayer' : IDL.Func([PlayerProfile], [], []),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getPlayerProfile' : IDL.Func([PlayerId], [PlayerProfile], ['query']),
  'getPlayerRaceResults' : IDL.Func(
      [PlayerId],
      [IDL.Vec(RaceResult)],
      ['query'],
    ),
  'getTrack' : IDL.Func([IDL.Nat], [Track], ['query']),
  'getTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
  'initializeTracks' : IDL.Func([], [], []),
  'submitRaceResult' : IDL.Func([RaceResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerId = IDL.Text;
  const PlayerStats = IDL.Record({
    'averagePosition' : IDL.Opt(IDL.Float64),
    'bestTime' : IDL.Opt(IDL.Nat),
    'racesCompleted' : IDL.Nat,
  });
  const PlayerProfile = IDL.Record({
    'id' : PlayerId,
    'nickname' : IDL.Text,
    'stats' : PlayerStats,
  });
  const Time = IDL.Int;
  const RaceResult = IDL.Record({
    'completionTime' : IDL.Nat,
    'playerId' : PlayerId,
    'trackId' : IDL.Nat,
    'timestamp' : Time,
    'position' : IDL.Nat,
  });
  const TrackDifficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Track = IDL.Record({
    'id' : IDL.Nat,
    'difficulty' : TrackDifficulty,
    'name' : IDL.Text,
    'length' : IDL.Nat,
  });
  
  return IDL.Service({
    'createPlayer' : IDL.Func([PlayerProfile], [], []),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getPlayerProfile' : IDL.Func([PlayerId], [PlayerProfile], ['query']),
    'getPlayerRaceResults' : IDL.Func(
        [PlayerId],
        [IDL.Vec(RaceResult)],
        ['query'],
      ),
    'getTrack' : IDL.Func([IDL.Nat], [Track], ['query']),
    'getTracks' : IDL.Func([], [IDL.Vec(Track)], ['query']),
    'initializeTracks' : IDL.Func([], [], []),
    'submitRaceResult' : IDL.Func([RaceResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };