/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PlayerId = string;
export interface PlayerProfile {
  'id' : PlayerId,
  'nickname' : string,
  'stats' : PlayerStats,
}
export interface PlayerStats {
  'averagePosition' : [] | [number],
  'bestTime' : [] | [bigint],
  'racesCompleted' : bigint,
}
export interface RaceResult {
  'completionTime' : bigint,
  'playerId' : PlayerId,
  'trackId' : bigint,
  'timestamp' : Time,
  'position' : bigint,
}
export type Time = bigint;
export interface Track {
  'id' : bigint,
  'difficulty' : TrackDifficulty,
  'name' : string,
  'length' : bigint,
}
export type TrackDifficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface _SERVICE {
  'createPlayer' : ActorMethod<[PlayerProfile], undefined>,
  'getLeaderboard' : ActorMethod<[], Array<PlayerProfile>>,
  'getPlayerProfile' : ActorMethod<[PlayerId], PlayerProfile>,
  'getPlayerRaceResults' : ActorMethod<[PlayerId], Array<RaceResult>>,
  'getTrack' : ActorMethod<[bigint], Track>,
  'getTracks' : ActorMethod<[], Array<Track>>,
  'initializeTracks' : ActorMethod<[], undefined>,
  'submitRaceResult' : ActorMethod<[RaceResult], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];