/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PlayerId = string;
export type Time = bigint;
export interface Track {
    id: bigint;
    difficulty: TrackDifficulty;
    name: string;
    length: bigint;
}
export interface PlayerProfile {
    id: PlayerId;
    nickname: string;
    stats: PlayerStats;
}
export interface RaceResult {
    completionTime: bigint;
    playerId: PlayerId;
    trackId: bigint;
    timestamp: Time;
    position: bigint;
}
export interface PlayerStats {
    averagePosition?: number;
    bestTime?: bigint;
    racesCompleted: bigint;
}
export enum TrackDifficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export interface backendInterface {
    createPlayer(profile: PlayerProfile): Promise<void>;
    getLeaderboard(): Promise<Array<PlayerProfile>>;
    getPlayerProfile(playerId: PlayerId): Promise<PlayerProfile>;
    getPlayerRaceResults(playerId: PlayerId): Promise<Array<RaceResult>>;
    getTrack(trackId: bigint): Promise<Track>;
    getTracks(): Promise<Array<Track>>;
    initializeTracks(): Promise<void>;
    submitRaceResult(result: RaceResult): Promise<void>;
}
import type { PlayerId as _PlayerId, PlayerProfile as _PlayerProfile, PlayerStats as _PlayerStats, Track as _Track, TrackDifficulty as _TrackDifficulty } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createPlayer(arg0: PlayerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(to_candid_PlayerProfile_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(to_candid_PlayerProfile_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<PlayerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerProfile(arg0: PlayerId): Promise<PlayerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProfile(arg0);
                return from_candid_PlayerProfile_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProfile(arg0);
            return from_candid_PlayerProfile_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerRaceResults(arg0: PlayerId): Promise<Array<RaceResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerRaceResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerRaceResults(arg0);
            return result;
        }
    }
    async getTrack(arg0: bigint): Promise<Track> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrack(arg0);
                return from_candid_Track_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrack(arg0);
            return from_candid_Track_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTracks(): Promise<Array<Track>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTracks();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTracks();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeTracks(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeTracks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeTracks();
            return result;
        }
    }
    async submitRaceResult(arg0: RaceResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRaceResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRaceResult(arg0);
            return result;
        }
    }
}
function from_candid_PlayerProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProfile): PlayerProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerStats_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerStats): PlayerStats {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TrackDifficulty_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackDifficulty): TrackDifficulty {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Track_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Track): Track {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    difficulty: _TrackDifficulty;
    name: string;
    length: bigint;
}): {
    id: bigint;
    difficulty: TrackDifficulty;
    name: string;
    length: bigint;
} {
    return {
        id: value.id,
        difficulty: from_candid_TrackDifficulty_n14(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        length: value.length
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlayerId;
    nickname: string;
    stats: _PlayerStats;
}): {
    id: PlayerId;
    nickname: string;
    stats: PlayerStats;
} {
    return {
        id: value.id,
        nickname: value.nickname,
        stats: from_candid_PlayerStats_n8(_uploadFile, _downloadFile, value.stats)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averagePosition: [] | [number];
    bestTime: [] | [bigint];
    racesCompleted: bigint;
}): {
    averagePosition?: number;
    bestTime?: bigint;
    racesCompleted: bigint;
} {
    return {
        averagePosition: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.averagePosition)),
        bestTime: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.bestTime)),
        racesCompleted: value.racesCompleted
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): TrackDifficulty {
    return "easy" in value ? TrackDifficulty.easy : "hard" in value ? TrackDifficulty.hard : "medium" in value ? TrackDifficulty.medium : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Track>): Array<Track> {
    return value.map((x)=>from_candid_Track_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerProfile>): Array<PlayerProfile> {
    return value.map((x)=>from_candid_PlayerProfile_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PlayerProfile_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerProfile): _PlayerProfile {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerStats_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerStats): _PlayerStats {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PlayerId;
    nickname: string;
    stats: PlayerStats;
}): {
    id: _PlayerId;
    nickname: string;
    stats: _PlayerStats;
} {
    return {
        id: value.id,
        nickname: value.nickname,
        stats: to_candid_PlayerStats_n3(_uploadFile, _downloadFile, value.stats)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averagePosition?: number;
    bestTime?: bigint;
    racesCompleted: bigint;
}): {
    averagePosition: [] | [number];
    bestTime: [] | [bigint];
    racesCompleted: bigint;
} {
    return {
        averagePosition: value.averagePosition ? candid_some(value.averagePosition) : candid_none(),
        bestTime: value.bestTime ? candid_some(value.bestTime) : candid_none(),
        racesCompleted: value.racesCompleted
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
